server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: login-service
          #uri: http://localhost:8081/
          uri: lb://Login-SERVICE
          predicates:
            - Path=/login/**
        - id: order-service
          #uri: http://localhost:8082/
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: product-service
          #uri: http://localhost:8083/
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.netflix: DEBUG
    org.springframework.cloud.gateway: DEBUG